### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by robert-hh** [robmarkcole/bme680-mqtt-micropython#2]
Hello Robin, since you dealt with the bme680, and you are a physicist, I have a question which you mitgh know an answer. Did you validate the values returned by the sensor? I used your code to compare it against the values returned by the adatfruit driver.
- temperature: identical within the promised error range
- humidity: identical, but both values are about 8% too high. 83.5% instead of 75.5% over a saturated NaCl solution, and similar for the "wet bulb" test (=pure water). I had a similar situation with an BME280, which reported 15% too low values. After re-conditioning, it's only 3% too low.
- pressure: Your driver seems fine, the adafruit's values are 10 hPa too high, compared to other sensors and the value reported by the university weather station, which is about the same level as my place (~10m higher = ~1 hpa less). I have to look into their code.

**Comment by robmarkcole** [comment]
Hi @robert-hh thanks for raising this question. I hadn't thought of doing any validation or 'comissioning' of the sensor, but if you want to make an absolute reading that would be required. I would suggest editing the code to accept 'callibration coefficients' to correct the readings. If you can write up a procedure for determining the coefficients I am happy to perform the measurement so we can compare values. Cheers
