### ISSUE TITLE
gas same value

### ISSUE THREAD

**Issue by jolugama** [robmarkcole/bme680-mqtt-micropython#3]
Hi, I have tried a simpler version of the bme680 and it worked. With this version the gas is always the same: 118898.4. The rest is correct. What could be wrong?

**Comment by robmarkcole** [comment]
`bme680.py` here is `__version__ = '1.0.2'` whilst [latest](https://github.com/pimoroni/bme680-python/blob/master/library/bme680/__init__.py) is `__version__ = '1.0.5'`, worth updating
